uf-mil/NaviGator

- gnc/navigator_controller/src/mrac_controller.py
- gnc/navigator_thrust_allocater/src/p_driver.py
- simulation/navigator_sim/navigator_sim_rendering/src/navigator_sim_rendering/sim_rendering_helpers.py
- utils/navigator_tools/navigator_tools/move_helper.py
Bugs fixed:
- move_helper function had current yaw in radians but accepted the yaw delta value in degrees
- thruster allocator call rate needed to be 50 Hz
- MRAC controller was multiplying gains and errors with * instead of np.dot
- weird murph_sim dependency in simulator didn't need to be there
Also:
- finished MRAC controller documentation
- tuned the PD parts of the MRAC controller at the lake
> GNC: bug fixes at lake day, and PD tuning

- gnc/navigator_controller/src/mrac_controller.py
- gnc/navigator_thrust_mapper/src/thrust_mapper.py
- mission_control/navigator_launch/launch/gnc.launch
- mission_control/navigator_launch/launch/simulation.launch
- simulation/navigator_sim/navigator_sim_model/src/navigator_sim_model/sim.py
There were a ton of places where mismatches in "which thrusters are where" (in a list of four of them) was causing chaos in the sim, and probably in real life. The unified standard is now:
BL, BR, FL, FR
(it's alphabetical, in case you forget)
I also fixed a bunch of other things:
- Thrust values in newtons were being sent straight to the thrusters. I multiplied in a conversion factor, which to my knowledge should map 220 N (measured max thrust) to 600 effort points (presumed max firmware value). This factor is a rosparam called effort_ratio.
- cos() and sin() of thruster angles in degrees were being taken, so I converted the angles to radians first.
- I replaced a manually implemented clip function with np.clip
- I deleted lines of code that did literally nothing
- The y-component of …
> THRUSTERS and SIM: fix thruster ordering, add effort scaling, fix B-matrix, update sim

- sensor_control/navigator_lidar/CMakeLists.txt
- sensor_control/navigator_lidar/package.xml
When building Navigator from a fresh install after following the wiki tutorial, I encountered this error:
`
/WORKSPACE/src/NaviGator/sensor_control/navigator_lidar/src/cluster_extraction.cpp:6:34: fatal error: navigator_msgs/Point.h: No such file or directory
#include "navigator_msgs/Point.h"
^
compilation terminated.
` 
I don't really understand ROS or the whole build process of this project yet, but after some digging around on google I found that adding the project that generates Point.h to the find_package thing in the lidar cmake file made the build work.
> Added navigator_msgs dependency to navigator_lidar

- sensor_control/navigator_lidar/CMakeLists.txt
Ensures navigator_msgs are generated before building lidar, even when building with several threads.
I thought I fixed this in fd3e7a3, but the issue still showed up when building with multiple threads, which is the default for catkin_make without specifying -j1.
> LIDAR: fix building with multiple threads

- scripts/bag_backup.sh
This bag backup script is similar to the one used on Sub8, but it has been changed to use locally mounted directories that can be passed as arguments from /etc/rc.local or the command line. I have added the line in the comments section of this file to /etc/rc.local with the variables set in properly. Testing was successful.
In the future, follow the instructions in the comments section of the script after test days to synchronize bag files to the external drive. Once the drive is in MIL, it would also be courteous to upload the files to the Samba server for everyone.
> SCRIPTS: Bag backup script

- perception/navigator_lidar_oa/readme.md
- perception/navigator_lidar_oa/src/ConnectedComponents.h
- perception/navigator_lidar_oa/src/OccupancyGrid.h
- perception/navigator_lidar_oa/src/VolumeClassifier.h
- perception/navigator_lidar_oa/src/lidar.cpp
Mostly cosmetic changes but wanted to get the readme in a PR for explanations of how to use the code. Here is a copy of the readme:
##Quick Overview
**Required Interfaces**
- /velodyne_points
- /odom
- /get_bounds
**Provided Interfaces**
- /ogrid
- /info_markers
- /database/objects
- /database/requests
- /unclassified_markers
**Interfaces for Debugging**
- /ira_persist
- /ira_frame
- /ira_pclcloud
##Quick Start Guide
**Starting the node**
- rosrun navigator_lidar_oa lidar
**Requesting objects from the database**
The service is name /database/requests with the input parameter name and will return the PerceptionObject message. Here are some example calls:
- rosservice call /database/requests "name: 'all'" 
- rosservice call /database/requests "name: 'shooter'"
- rosservice call …
> Lidar: new readme with guide on how to use node

- gnc/navigator_msg_multiplexer/CMakeLists.txt
- gnc/navigator_msg_multiplexer/cfg/OgridConfig.cfg
- gnc/navigator_msg_multiplexer/launch/ogrid_server.launch
- gnc/navigator_msg_multiplexer/nodes/ogrid_arbiter.py
- mission_control/navigator_alarm/navigator_alarm/__init__.py
- mission_control/navigator_alarm/navigator_alarm/alarm_helpers.py
- mission_control/navigator_alarm/nodes/alarm_handler.py
- mission_control/navigator_launch/launch/subsystems/lqrrt_node.launch
- mission_control/navigator_missions/nav_missions/__init__.py
- mission_control/navigator_missions/nav_missions/coral_survey.py
- mission_control/navigator_missions/nav_missions/start_gate.py
- mission_control/navigator_missions/navigator_singleton/navigator.py
- mission_control/navigator_missions/navigator_singleton/pose_editor.py
- mission_control/navigator_missions/navigator_singleton/vision_services.yaml
- mission_control/navigator_missions/nodes/move_command
- mission_control/navigator_missions/nodes/run_mission
- utils/navigator_tools/navigator_tools/general_helpers.py
- Added `fprint` to do some cool fancy printing without 3rd party libraries. You'll notice any mission running or anything that uses the Navigator Singleton will have titles and fancy blue and green text.
- `move.(...).go()` commands will tell you if lqrrt actually got us there or if there was a problem with the trajectory.
- Improved `start_gate` missions and wrote `coral_survey` mission. `coral_survey` right now will take rosparam quadrants to search and simply go to the middle of that quadrant (though better search patterns would be pretty trivial). It requires a fake service server to return found shapes right now.
- Ogrid arbiter is a thing and can take an arbitrary number of ros occupancy grids and combine them! The ogrids can be arbitrarily sized and positioned but _must_ have the …
> OGRID, MISSIONS, TOOLS

- mission_control/navigator_missions/nav_missions/detect_deliver.py
- mission_control/navigator_missions/navigator_singleton/mission_params.yaml
- mission_control/navigator_missions/navigator_singleton/navigator.py
Addresses #117 
Adds an object to the navigator mission object similar to the vision services dictionary, where missions can get a param by an index, which gets the corresponding param in the yaml file, checking that its value is one of the valid values. Also has the added benefit of forcing us to document which params we are going to use for missions. The mission planner (what is the status on that anyways?) could use this same yaml file or the parsed dictionary itself to make decisions about when to run missions.
> MISSIONS: navigator object provides methods for missions to safely get yaml defined paramters

- gnc/navigator_msg_multiplexer/nodes/wrench_arbiter.py
- install.sh
- mission_control/navigator_launch/launch/gnc.launch
- utils/navigator_battery_monitor/package.xml
- utils/navigator_gui/navigator_gui/dashboard.py
- utils/navigator_msgs/CMakeLists.txt
- utils/navigator_msgs/srv/KeyboardControl.srv
- utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
- utils/remote_control/navigator_joystick_control/package.xml
- utils/remote_control/navigator_keyboard_control/CMakeLists.txt
- utils/remote_control/navigator_keyboard_control/nodes/navigator_keyboard_client.py
- utils/remote_control/navigator_keyboard_control/nodes/navigator_keyboard_server.py
- utils/remote_control/navigator_keyboard_control/package.xml
- utils/remote_control/navigator_keyboard_control/remote_control_lib/__init__.py
- utils/remote_control/navigator_keyboard_control/remote_control_lib/remote_control_lib.py
- utils/remote_control/navigator_keyboard_control/setup.py
This PR mainly cleaned up and refactored the remote control system. With the creation of the controller library, any basic interface to a controller (GUI, keyboard, joystick, etc.) can access all of our remote control functions without having to re-implement them locally.
Keyboard control was implemented using a client-server architecture in which one user at a time can 'lock' control of the server by pressing Shift+L. The client does not unlock control, control can be taken by a new keyboard at any time (this is to avoid someone locking control and then leaving without unlocking). All of the key bindings are printed in a help menu. It can be run in a terminal with this command (this includes the terminal emulator in RQT so that the user can drive with cameras or RVIZ in the same window): …
> REMOTE_CONTROL: Controller library and keyboard control

- mission_control/navigator_missions/nav_missions/circle.py
- mission_control/navigator_missions/navigator_singleton/pose_editor.py
- mission_control/navigator_missions/nodes/move_command
- mission_control/navigator_missions/nodes/run_mission
- simulation/navigator_gazebo/include/navigator_gazebo/navigator_state_set.hpp
- simulation/navigator_gazebo/launch/goose.launch
- simulation/navigator_gazebo/models/wamv/wamv.sdf
- simulation/navigator_gazebo/nodes/gazebo_controller.py
- simulation/navigator_gazebo/src/navigator_state_set.cpp
- utils/navigator_tools/navigator_tools/msg_helpers.py
Adds support for lqrrt circles. Also fixes most of the gazebo issues I've been having.
__Some important things to note for missions__
- The move formally known as `circle_point` no longer circles a point in discrete move commands like it used to. To keep the same functionality as before (discrete move commands) use `d_circle_point`. The new `circle_point` continuously circles a point at the boat's current distance to the point and the relative orientation to the point. This move will not actively avoid obstacles and will instead return a failure if an obstacle is detected.
- `navigator.move.(...).go()` now returns the action result. The action result has a `failure_reason` attribute which is normally blank (unless something went wrong). 
- Let me know if you have any other questions!
> COMMAND: Circles!

- .gitignore
- gnc/navigator_msg_multiplexer/nodes/wrench_arbiter.py
- hardware_drivers/navigator_kill_board/CMakeLists.txt
- hardware_drivers/navigator_kill_board/nodes/driver_node.py
- hardware_drivers/navigator_kill_board/package.xml
- mission_control/navigator_alarm/navigator_alarm/__init__.py
- mission_control/navigator_alarm/navigator_alarm/alarm_helpers.py
- mission_control/navigator_alarm/nodes/alarm_handler.py
- mission_control/navigator_alarm/nodes/event_listeners/odom_kill_listener.py
- mission_control/navigator_alarm/test_alarms/test.py
- mission_control/navigator_launch/launch/subsystems/hardware_drivers.launch
- mission_control/navigator_missions/nav_missions/circle.py
- mission_control/navigator_missions/nav_missions/circle_tower.py
- mission_control/navigator_missions/navigator_singleton/__init__.py
- mission_control/navigator_missions/navigator_singleton/navigator.py
- mission_control/navigator_missions/navigator_singleton/pose_editor.py
- mission_control/navigator_missions/nodes/move_command
- utils/navigator_msgs/CMakeLists.txt
- utils/navigator_msgs/msg/KillStatus.msg
- utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
- utils/remote_control/navigator_keyboard_control/remote_control_lib/remote_control_lib.py
Some noteworthy things changed in this PR:
- Meta alarms require none of the "sub" alarms that could raise them are raised in order for the meta alarm to be cleared. For example, if the `kill` meta-alarm is triggered by the `rc_kill` and `hw_kill` alarms, both of those alarms must be clear in order for the `kill` alarm to also be clear. This was important for the kill board node.
- Speaking of, the kill board node is here and it connected with Daniel Duggers kill board to connect it with ROS. I tested different control methods (RC and Autonomous) to make sure it lit up correctly. Also I tested different alarm set ups, everything seemed to work.
- One weird thing I did was not include `odom_kill` in the kill meta alarm because this would effectively disable RC mode if odom went down - …
> KILL: Add kill board package and update alarms

- mission_control/navigator_launch/CMakeLists.txt
- mission_control/navigator_launch/launch/subsystems/cameras/cameras.launch
- mission_control/navigator_launch/launch/subsystems/cameras/front_stereo.launch
- mission_control/navigator_launch/package.xml
- mission_control/navigator_missions/nav_missions/detect_deliver.py
- mission_control/navigator_missions/navigator_singleton/navigator.py
- perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.cpp
- As detect deliver runs, it remembers what shapes it saw. If after circling around the platform the correct shape/color is not identified, it will shoot in one of the targets it saw while circling
- Catch some potential edge case errors in CameraLidarTransformer
- Update the Searcher class in navigator to take a custom looking callback. I don't think anyone else uses this, so it won't break anything.
- Everything has been tested in bags without any regressions
> DETECT DELIVER: Shoot in random shape if correct not found

- mission_control/navigator_launch/launch/bag.launch
- mission_control/navigator_launch/launch/perception.launch
- mission_control/navigator_launch/launch/subsystems/perception/dock_shapes_front.launch
- mission_control/navigator_launch/launch/subsystems/perception/shape_finder.yaml
- mission_control/navigator_launch/launch/subsystems/perception/shape_finder_front.yaml
- mission_control/navigator_missions/nav_missions/detect_deliver.py
- mission_control/navigator_missions/nav_missions/identify_dock.py
- mission_control/navigator_missions/nav_missions/pinger.py
- mission_control/navigator_missions/navigator_singleton/navigator.py
- mission_control/navigator_missions/navigator_singleton/vision_services.yaml
- mission_systems/shooter/nodes/ShooterControl.py
- perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.cpp
- perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.hpp
- perception/navigator_vision/nodes/shape_identification/ShapeTracker.cpp
- perception/navigator_vision/nodes/shape_identification/TrackedShape.cpp
- perception/navigator_vision/nodes/shape_identification/main.cpp
- simulation/navigator_gazebo/nodes/sim_hydrophones.py
- utils/navigator_msgs/CMakeLists.txt
- utils/navigator_msgs/srv/GetDockBays.srv
- Shooter does not listen to kill (for real this time)
- Pinger now circles totem 30 meters away, and move much more smoothly with drive mode and smooth circles
- Detect Deliver smooth circles until finding one shape, then uses that normal to look at the other shapes if necessary
- Add identify and dock mission. For now, just circles around fake "Dock" object looking for correct shapes, then aligns based on the normals to those shapes (like detect deliver)
- And hydrophone service faker for sim
- Identify and dock has skeleton code for working with the more advanced options being developed by @RustyBamboo and @whispercoros to publish a special dock mission ogrid and identify the dock bays with ogrid/lidar rather than vision.
- Shapes perception and camera to lidar normal had been made …
> PINGER, DOCKING, DETECT DELIVER, SHOOTER, PERCEPTION, TOOLS: kevins work from compeition through 12/14

- Jenkinsfile
- scripts/Dockerfile
These are the files necessary to get the CI working. Once kinetic-upgrade is deployed this will be deployed alongside it and I can build the image on plumbusi. Until then, trying to force this in before cmake works will only cause problems with existing CI operations. 
This is mainly due to the fact both Jenkins and Docker rely on the install script which still points to the master branch. Otherwise there may be some issues with the SDK for point gray, but that should be a near instant fix if said issue crops up. It doesn't seem like it will, thanks to the install script, but it is worth noting.
> CI: Add Jenkins and Dockerfile

- mission_control/navigator_launch/launch/gnc.launch
- scripts/bash_aliases.sh
I was thinking about if we should start in autonomous or rc mode by default. I think the best option is to start with no wrench selected, we we have to explicitly set to rc or autonomous before moving. Also added a alias nwrench for selecting wrench, with tab completion (booya!)
> WRENCH: default to no wrench selected for safety

- mission_control/navigator_launch/launch/gnc.launch
- mission_control/navigator_launch/launch/simulation.launch
* it is now already included in gnc.launch
Didn't see this before I merged #251. My B!
> LAUNCH: remove path planner duplicate in simulation.launch

- scripts/bagging_variables.sh
* gives more info about when messages arrived, even if aggregator is not running
> BAGGING: bag /diagnostics instead of /diagnostics_agg

- hardware_drivers/navigator_kill_board/navigator_kill_board/constants.py
- hardware_drivers/navigator_kill_board/navigator_kill_board/simulated_kill_board.py
- Rename 'REMOTE' kill constant with 'HEARTBEAT_COMPUTER' constant
- Add 'BUTTON_REMOTE' and 'HEARTBEAT_REMOTE' constants to reflect changes to data sent by kill board microprocessor
- These changes don't alter the actual kill functionality, only report more accurately the source of the kill
> KILL BOARD: replace remote constant with heartbeats and button constants

- gnc/navigator_thrust_mapper/nodes/thrust_mapper.py
- hardware_drivers/navigator_kill_board/nodes/kill_board_driver.py
- utils/navigator_battery_monitor/nodes/navigator_battery_monitor.py
**depends on uf-mil/ros_alarms#40**
Nodes now wait on the alarm server if it is not up, to reduce weird timing dependent things.
> ALARMS: wait for alarms

- utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
We've had this problem at lakedays where when the xbox controller self shuts off and comes back online, it incorrectly reports buttons being pressed (specifically the kill button), causing a kill. Since this problem seems to go down to the driver level, I've made a higher level solution. Press the "back" button and the remote control node will ignore the controller until start is held down. So if you're going to turn off the controller/not use it for a while, press back.
> REMOTE CONTROL: go inactive when back pressed

- scripts/bash_aliases.sh
closes #321 
Adds an alias bag-fast to bag to a directory on the SSD which has sufficient write speed to handle high bandwidth topics. Then use aliases syncbags and purgebagfast to sync the SSD bags to the external HDD and clear the ones on the SSD.
> ALIASES: add bag-fast alias to bag to SSD

- mission_control/navigator_launch/launch/hardware/cameras/seecam.launch
The seecam in the front left is now a different unit, and has a different ID
> CAMERAS: update id on seecam

- scripts/Dockerfile
Because certain networks (like uf) cache's apt repos, sometimes the Docker container failed to build
> DOCKER: clear cache before updating apt

- gnc/navigator_thrust_mapper/navigator_thrust_mapper/thruster_map.py
- gnc/navigator_thrust_mapper/nodes/thrust_mapper.py
- mission_control/navigator_launch/launch/gnc/tf.launch
- mission_control/navigator_launch/launch/gnc/thruster_mapper.launch
- mission_control/navigator_launch/package.xml
- perception/navigator_lidar_oa/CMakeLists.txt
- perception/navigator_lidar_oa/package.xml
- simulation/navigator_2dsim/sim2d.py
- simulation/navigator_gazebo/urdf/thruster.xacro
Depends on #355 
Load the thruster poses from the URDF, so they are not copied in two places.
> GNC: refactor thruster_map to use URDF

- scripts/bagging_variables.sh
- scripts/on_boot
* Now running on v0.10.1, this flag is needed for our older unit
> BOOT: add use-imu1 flag for compatibility with newer sdgps version

- simulation/navigator_gazebo/CMakeLists.txt
- simulation/navigator_gazebo/include/navigator_gazebo/pinger_plugin.hpp
- simulation/navigator_gazebo/models/robotx_pinger/model.config
- simulation/navigator_gazebo/models/robotx_pinger/model.sdf
- simulation/navigator_gazebo/src/pinger_plugin.cpp
- simulation/navigator_gazebo/urdf/navigator.urdf.xacro
- simulation/navigator_gazebo/worlds/course.world.xacro
depends on uf-mil/mil_common#139
Adds a pinger to gazebo. you can call a service to switch which gate it's in and it will publish a heading from NaviGator to the heading (using ground truth so high level mission code can be tested)
> SIMULATION: add simulated pinger w/ ground truth heading

- mission_control/navigator_launch/launch/hardware/cameras/front_cameras.launch
- mission_control/navigator_launch/launch/hardware/cameras/front_left.launch
At lakeday we discovered front_left has the wrong ID. Once it was fixed, we couldn't run front_left and starboard at same time (thank pointgrey), so disable front_left for now.
> CAMERAS: fix front_left serial id and disable it

- mission_control/navigator_launch/launch/hardware.launch
- mission_control/navigator_launch/launch/hardware/pneumatic_actuators.launch
- mission_control/navigator_launch/package.xml
- mission_control/navigator_missions/launch/task_runner.launch
- mission_control/navigator_missions/navigator_missions/__init__.py
- mission_control/navigator_missions/navigator_missions/deploy_thrusters.py
- mission_control/navigator_missions/navigator_missions/fire_launcher.py
- mission_control/navigator_missions/navigator_missions/navigator.py
- mission_control/navigator_missions/navigator_missions/reload_launcher.py
- mission_control/navigator_missions/navigator_missions/retract_thrusters.py
- scripts/bash_aliases.sh
- utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
- utils/remote_control/navigator_keyboard_control/remote_control_lib/remote_control_lib.py
depends on uf-mil/mil_common#135
closes #385 
The follow changes are added to support remote thruster deploy/retraction
* Launch the actuator driver with the configuration for the thrusters
* Write missions to actuate the valves to allow for thruster deploy/retraction
* Connect the LB and RB buttons on xbox controller to retract and deploy thrusters, respectively
> MISSIONS: integrate thruster autodeploy / launcher into launch & missions
