gnc/navigator_controller/src/mrac_controller.py, utils/navigator_tools/navigator_tools/move_helper.py
Lake day: 4/1/2016
- Switch on adaptive control
- Allow MRAC's built in trajectory generator to use asymmetric velocity limits
- Make move_helper take incremental commands in body-frame, so like x=10 means move *forward* 10 meters, not move East 10 meters.
=> CONTROLLER and INTERFACE: lake day changes

gnc/navigator_controller/README.md, gnc/navigator_controller/src/mrac_controller.py, gnc/navigator_controller/src/run_nn_controller, mission_control/navigator_launch/launch/gnc.launch, simulation/navigator_sim/navigator_sim_model/src/navigator_sim_model/sim.py, utils/navigator_tools/navigator_tools/move_helper.py
Everything worked at the lake, and I also have it all working in simulation too.
- new NN controller option (if you want to use it, update the dependency list)
- final (probably) tuning of MRAC controller
- new MRAC feature: subscribes to a Bool /mrac_learn to start and stop learning (defaults to stopped)
- option to use C3 trajectory generator from sub instead of the built-in one in MRAC (the NN_controller, on the other hand, must use an external trajectory generator like C3; there is none built in).
I left the system set up to use MRAC with internal trajectory generator, as it is compatible with Zach's gui and is a lot more predictable.
=> Lake Day 4/23/16

simulation/navigator_gazebo/CMakeLists.txt, simulation/navigator_gazebo/launch/goose.launch, simulation/navigator_gazebo/models/shapes/scan_the_code.sdf, simulation/navigator_gazebo/src/animated_box.cc, simulation/navigator_gazebo/src/animated_box.h
=> Scan the code simulation fix

gnc/navigator_thrust_mapper/nodes/thrust_mapper.py, mission_control/navigator_launch/launch/master_boat.launch, mission_control/navigator_launch/launch/subsystems/tf.launch
This should fix the "17 commits behind" thing in dev.
Also fixes #45 - albeit it's a patch at best.
PR 69 is best PR
=> Updates from lake day

mission_control/navigator_launch/launch/simulation.launch, mission_control/navigator_missions/navigator_singleton/__init__.py, mission_control/navigator_missions/navigator_singleton/navigator.py, mission_control/navigator_missions/navigator_singleton/pose_editor.py, mission_control/navigator_missions/navigator_singleton/vision_services.yaml, mission_control/navigator_missions/nodes/move_command, mission_control/navigator_missions/nodes/run_mission, utils/navigator_msgs/CMakeLists.txt, utils/navigator_msgs/srv/Bounds.srv, utils/navigator_msgs/srv/CoordinateConversion.srv, utils/navigator_tools/navigator_tools/image_helpers.py, utils/navigator_tools/nodes/bounds.py, utils/navigator_tools/nodes/coordinate_conversion_server.py, utils/navigator_tools/nodes/tf_fudger.py, utils/on_boot/launch/boot.launch
Added services to:
- Convert between different global frames (from `enu`, `lla`, or `ecef` to all the others. 
- Request the current GPS bounds in whatever global frame you want
Note, both the coordinate conversion script and bounds server script must be running to have access to either of these services
=> GPS Bounds and Coordinate Conversion

mission_systems/shooter/launch/config.yaml, mission_systems/shooter/nodes/ShooterControl.py
Longer tract + extend time to avoid jams
cancel and manual callback dont throw error
Serial port set to by-id (not sure if this will be same on boat)
=> SHOOTER: Tuned timing vals/bug fixes

mission_systems/shooter/nodes/ShooterControl.py
This is what caused the shooter to not shoot on 10/09
=> SHOOTER: Fatal syntax bug fix

mission_control/navigator_launch/launch/subsystems/hydrophones.launch, mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/__init__.py, mission_control/navigator_missions/nav_missions/explore.py, mission_control/navigator_missions/nav_missions/start_gate.py, mission_control/navigator_missions/nav_missions/teleop.py, mission_control/navigator_missions/navigator_singleton/navigator.py, mission_control/navigator_missions/navigator_singleton/pose_editor.py, mission_control/navigator_missions/nodes/run_mission, utils/navigator_tools/nodes/tf_fudger.py
The start gate mission ran on lake day 10-15 but required the database to be online.
The TF for the front stereo should be more correct but will be further refined at the next lake day.
I was also having some canceling issues with un-yielded defers. It looked like twisted was not recursively canceling like it was supposed to (or maybe I just need to wrap things in more error callbacks).
=> MISSIONS: Start gate and teleop

install.sh, utils/navigator_gui/navigator_gui/dashboard.py
This sets up ros_connect to work with the secondary computer on NaviGator and installs some missing git repositories. It also includes a few bug fixes for the dashboard that are too small for a separate PR.
=> SCRIPTS: Minor changes to the install script

mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/approach_pinger.py, mission_control/navigator_missions/nav_missions/coral_survey.py, mission_control/navigator_missions/nav_missions/start_gate.py, mission_control/navigator_missions/navigator_singleton/navigator.py, utils/navigator_tools/nodes/tf_fudger.py
Changes David and I made on lakeday. It appears as if the TF for the left camera isn't accurate but the right camera TF is incredibly precise. 
There are some changes to the missions in here to in order to fix bugs and what not.
After this PR we will do a dev->master merge.
=> Lake day 10-30

mission_control/navigator_launch/launch/subsystems/perception/dock_shapes.launch, mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/detect_deliver.py, mission_control/navigator_missions/navigator_singleton/mission_params.yaml, mission_systems/shooter/launch/config.yaml, mission_systems/shooter/nodes/Sabertooth2x12.py, mission_systems/shooter/nodes/ShooterControl.py, perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.cpp, perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.hpp, perception/navigator_vision/nodes/shape_identification/DockShapeVision.cpp, perception/navigator_vision/nodes/shape_identification/DockShapeVision.h, perception/navigator_vision/nodes/shape_identification/GrayscaleContour/GrayscaleContour.cpp, simulation/navigator_gazebo/models/wamv/wamv.sdf, utils/navigator_tools/nodes/tf_to_gazebo.py, utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
Commit messages for more info.
=> DD fixes, Sim sensor poses, TF from lakeday, tools

simulation/navigator_gazebo/launch/goose.launch, simulation/navigator_gazebo/models/markers/white_marker_line.dae, simulation/navigator_gazebo/models/markers/white_marker_line.sdf
This just adds in the last model that was needed to simulate the complete course. The sandbox world is now considered finished.
=> SIM: Sandbox Simulator Finishing Touches

mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/pinger.py, mission_control/navigator_missions/navigator_singleton/mission_params.yaml
From lakeday 11/12-11/13
1.  Fix tf for hydrophones
2. Add pinger finder perception which locates pingers
3. Add mission to go to gates, locate pinger, and go through correct gate
=> ACOUSTIC PINGER: Add pinger perception and mission

mission_control/navigator_launch/launch/perception.launch, mission_control/navigator_launch/launch/simulation.launch, mission_control/navigator_launch/launch/subsystems/hardware_drivers.launch, mission_control/navigator_launch/launch/subsystems/shooter.launch, mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/detect_deliver.py, mission_control/navigator_missions/nav_missions/pinger.py, mission_control/navigator_missions/navigator_singleton/mission_params.yaml, mission_control/navigator_missions/navigator_singleton/navigator.py, mission_systems/shooter/nodes/ShooterControl.py, perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.cpp, perception/navigator_vision/nodes/camera_to_lidar/CameraLidarTransformer.hpp, perception/navigator_vision/nodes/pinger_finder.py, utils/navigator_msgs/action/ShooterDo.action, utils/navigator_tools/nodes/clicked_point_recorder.py, utils/navigator_tools/nodes/video_player.py
- start the flywheels spinning up when the shooter starts loading
- add TF for shooter (where the ball leaves the flywheels), so we can align based on shooter location not base_link
- Clean camera_to_lidar so it does not bring great shame to my family
- Matthew langford fixed a bug with importing something something __init
- Can set a param to align to the big or small goal in detect deliver
=> DETECT DELIVER: Lakeday fixes, better alignment

install.sh, scripts/mil_aliases.sh
**This is a work in progress, please do not merge until this warning is removed and I give the all clear**
These commits address the following:
* The install process for gcc-arm-embedded was not the same as for other PPA's in the script
* There was a build issue on Semaphore due to the script pulling the kinetic-devel branch of gazebo_ros_pkgs as opposed to the indigo-devel branch
* The install script rewrote the users entire ~/.bashrc file to update it
The install script now makes sure to pull the correct branch from gazebo_ros_pkgs and will now install all custom bashrc aliases to ~/.mil_aliases. This file is copied directly from /scripts/mil_aliases.bash in the repository, so feel free to add useful commands to it so long as they are not tied to a specific workspace directory.
=> INSTALL: Fixes all of the recently discovered issues with the install process

mission_control/navigator_missions/nav_missions/start_gate.py, mission_control/navigator_missions/nodes/move_command, perception/navigator_vision/nodes/database_color.py, simulation/navigator_gazebo/nodes/gazebo_controller.py
- Fixed a start gate bug that should result in more stable performance with 2 or 4 gates discovered.
- Fixed a quark in the gazebo controller where it was trying to math at 1000hz
- Made various changes to how the database color node works. Still more to come here.
=> NAVC, GAZEBO, START_GATE

mission_control/navigator_launch/launch/perception.launch, mission_control/navigator_missions/nav_missions/coral_survey.py, mission_control/navigator_missions/nav_missions/detect_deliver.py, mission_control/navigator_missions/nav_missions/identify_dock.py, mission_control/navigator_missions/nav_missions/pinger.py, mission_control/navigator_missions/navigator_singleton/mission_params.yaml, perception/navigator_vision/nodes/shooter_finder.py, utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
- includes @forrestv's detect deliver tracker
- no more shoot through controller
- set gate param based on color
=> MISSIONS: Saturday fixes to pinger, detect deliver, identify dock

hardware_drivers/navigator_kill_board/nodes/driver_node.py, mission_control/navigator_alarm/navigator_alarm/__init__.py, mission_control/navigator_alarm/nodes/event_listeners/keepalive_listener.py, mission_control/navigator_missions/nav_missions/circle_tower.py, test/navigator_test/nodes/circle_sim.py
=> KILL, TOTEMS

mission_control/navigator_launch/config/stereo_shape_detector.yaml, mission_control/navigator_launch/launch/bag.launch, mission_control/navigator_launch/launch/simulation.launch, mission_control/navigator_launch/launch/subsystems/cameras/cameras.launch, mission_control/navigator_launch/launch/subsystems/cameras/downward.launch, mission_control/navigator_launch/launch/subsystems/cameras/front_cameras.launch, mission_control/navigator_launch/launch/subsystems/cameras/starboard.launch, mission_control/navigator_launch/launch/subsystems/perception/dock_shapes.launch, mission_control/navigator_launch/launch/subsystems/perception/dock_shapes_front.launch, mission_control/navigator_launch/launch/subsystems/tf.launch, mission_control/navigator_missions/nav_missions/identify_dock.py, mission_systems/navigator_find_the_break/find_the_break_perception.py, mission_systems/navigator_scan_the_code/navigator_scan_the_code/scan_the_code_lib/scan_the_code_perception.py, mission_systems/navigator_scan_the_code/navigator_scan_the_code/scan_the_code_mission.py, navigator.rviz, perception/navigator_vision/nodes/database_color.py, perception/navigator_vision/nodes/start_gate_manual.py, perception/navigator_vision/object_classification/lidar_to_image.py, scripts/bagging_variables.sh, simulation/navigator_gazebo/models/wamv/wamv.sdf, utils/navigator_tools/navigator_tools/self_check.py
* Modified appropriate scripts and python files
* Use pointgrey driver
Camera topics:
* stereo/left -> /camera/front/left
* stereo/right -> /camera/front/right
* right/right -> /camera/starboard/front
* down/down -> /camera/down/down
TF topics:
* stereo_left_cam -> front_left_cam
* stereo_right_cam -> front_right_cam
* right_right_cam -> starboard_front_cam
Tested in SIM using kinetic-upgrade branch
Reference to #200
=> CAMERAS: rename camera topics and tf

.gitmodules, gnc/navigator_msg_multiplexer/nodes/ogrid_arbiter.py, gnc/navigator_path_planner/CMakeLists.txt, gnc/navigator_path_planner/README.md, gnc/navigator_path_planner/action/Move.action, gnc/navigator_path_planner/navigator_path_planner/__init__.py, gnc/navigator_path_planner/navigator_path_planner/boat.py, gnc/navigator_path_planner/navigator_path_planner/car.py, gnc/navigator_path_planner/navigator_path_planner/escape.py, gnc/navigator_path_planner/navigator_path_planner/params.py, gnc/navigator_path_planner/nodes/lqrrt_node.py, gnc/navigator_path_planner/package.xml, gnc/navigator_path_planner/setup.py, mission_control/navigator_alarm/navigator_alarm_handlers/station_hold.py, mission_control/navigator_launch/README.md, mission_control/navigator_launch/launch/simulation.launch, mission_control/navigator_launch/launch/subsystems/path_planner.launch, mission_control/navigator_missions/navigator_singleton/navigator.py, mission_control/navigator_missions/navigator_singleton/pose_editor.py, utils/navigator_tools/nodes/fake_action_server.py
I didn't like how we were handling our use of lqrRRT, where we just run the ROS demo in that repository (which may change and not be inline with NaviGator specific needs). It also requried us manually run a setup.py as lqRRT is not a catkin package. This addresses both of those problems, by cloning the current lqRRT ROS Demo into the repository so we can develop it in NaviGator in the future (or replace it with a different path planner).
=> PATH PLANNER: clone lqrrt node into repo

readme.md
=> README: add slack link

scripts/bagging_variables.sh
=> BAGGING: always bag tf

mission_control/navigator_alarm/navigator_alarm_handlers/station_hold.py, utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py, utils/remote_control/navigator_keyboard_control/remote_control_lib/remote_control_lib.py
* clean up joystick code
* turn off wrench cycle button (what was its purpose?)
* turn off auto set wrench to rc on kill (why?? just confusing)
* clean up and test station-hold alarm
=> REMOTE CONTROL: make B kill, X revive, not toggle kill

mission_control/navigator_alarm/navigator_alarm_handlers/kill.py, mission_control/navigator_launch/launch/master_boat.launch, mission_control/navigator_launch/launch/online_bagger.launch, scripts/bagging_variables.sh
=> BAG: integrate online bagger into launch and kill system

mission_control/navigator_missions/CMakeLists.txt, mission_control/navigator_missions/nav_missions_test/test_import_missions.py, mission_control/navigator_missions/navigator_singleton/navigator.py, mission_control/navigator_missions/test/import_missions.test
- Attempts to import Navigator singleton and each individual mission, failing if there is an import error
=> TEST: add integration test to check syntax errors in missions

utils/navigator_gui/navigator_gui/dashboard.py, utils/navigator_gui/navigator_gui/host_monitor.py, utils/navigator_gui/navigator_gui/shooter.py
Can someone else verify that that navigator GUI works on 16.04 with this change? Build, open rqt, and add the NaviGator gui as a plugin (suggest running simulation first)
Edit: I just mean works initially like you can see the interface and buttons. It might freeze or segfault after some time as it has always done...
=> GUI: fix Qt API change in 16.04

utils/navigator_tools/nodes/boat_info.py
* if first message arrived very quickly, would throw an error
=> TOOLS: hotfix for boat info tool

simulation/navigator_gazebo/CMakeLists.txt, simulation/navigator_gazebo/test/CMakeLists.txt, simulation/navigator_gazebo/test/sim_integration.test, simulation/navigator_gazebo/test/test_sim_integration.py
A completed basic sim integration test.  This tests initial odometry, camera, and lidar data.
=> TEST: Sim Integration Test

readme.md
Will need Jenkins to build the master branch
=> CI: Replace semaphore build status with Jenkins'

hardware_drivers/navigator_kill_board/nodes/kill_board_driver.py
* as per Davids recommendation
=> KILL BOARD: only kill on overall True

mission_control/navigator_alarm/navigator_alarm_handlers/kill.py, scripts/bash_aliases.sh
=> KILL: set problem description in kill alarm

gnc/navigator_msg_multiplexer/nodes/ogrid_arbiter.py, perception/navigator_lidar_oa/CMakeLists.txt, perception/navigator_lidar_oa/package.xml, perception/navigator_lidar_oa/src/lidar.cpp, utils/navigator_msgs/CMakeLists.txt, utils/navigator_msgs/srv/Bounds.srv, utils/navigator_tools/cfg/BoundsConfig.cfg, utils/navigator_tools/cfg/channel.yaml, utils/navigator_tools/cfg/course_a.yaml, utils/navigator_tools/cfg/course_b.yaml, utils/navigator_tools/cfg/course_c.yaml, utils/navigator_tools/cfg/sim.yaml, utils/navigator_tools/cfg/wauberg.yaml, utils/navigator_tools/nodes/bounds.py
* address #253, probably (at least I know how to configure it to work at test days now)
* this will break the missions ATM, b/c I don't want to change code that will be replaced in #274 (COUGH COUGH REVIEW IT)
* dynamic reconfigure now does bounds in ENU too
* remove /get_bounds service so everyone uses dynamic reconfigure like proper citizens
* update navigator lidar_oa and ogrid_arbiter to work with this change
* other small bug fixes
* depends on uf-mil/mil_common#98
=> BOUNDS: refactor bounds server

mission_control/navigator_launch/launch/gnc.launch, utils/navigator_msgs/srv/CoordinateConversion.srv, utils/navigator_tools/nodes/bounds.py, utils/navigator_tools/nodes/coordinate_conversion_server.py
=> TOOLS: refactor coordinate conversion server

Jenkinsfile, hardware_drivers/navigator_kill_board/test/kill_board_test.py, mission_control/navigator_alarm/navigator_alarm_handlers/kill.py, mission_control/navigator_launch/package.xml, mission_control/navigator_missions/navigator_missions/navigator.py, mission_control/navigator_missions/package.xml, perception/navigator_lidar_oa/src/lidar.cpp
depends on uf-mil/mil_common#101
Address #299. Should be getting a lot more green checks after this
=> CI: only run tests in NaviGator

mission_control/navigator_launch/launch/gnc.launch, mission_control/navigator_missions/navigator_missions/__init__.py, mission_control/navigator_missions/navigator_missions/move.py, mission_control/navigator_missions/navigator_missions/navigator.py, mission_control/navigator_missions/navigator_missions/pinger_andy.py, mission_control/navigator_missions/navigator_missions/start_gate_andy.py
TODO:
* add some more comments
=> MISSIONS: add mission to go through start gate using Andy's sonar

simulation/navigator_2dsim/launch/owl.launch
=> 2D SIM: update drag coefficents from bag data

gnc/navigator_thrust_mapper/CMakeLists.txt, gnc/navigator_thrust_mapper/navigator_thrust_mapper/__init__.py, gnc/navigator_thrust_mapper/navigator_thrust_mapper/thruster_map.py, gnc/navigator_thrust_mapper/nodes/thrust_mapper.py, gnc/navigator_thrust_mapper/setup.py, mission_control/navigator_launch/launch/subsystems/thruster_mapper.launch, simulation/navigator_2dsim/sim2d.py
* Degoinesify thruster mapper so it is clearer what it does and how it works
* Separate ROS component of thruster mapper from math part, so other programs (like 2D sim) can use the mapping functionality
* Update 2D sim to simulate each individual thruster instead of the whole body wrench. Now the kinematic full system is simulated! #312
=> 2D SIM: simulate individual thruster forces

Jenkinsfile, scripts/bash_aliases.sh, utils/navigator_tools/nodes/sylphase_ros_driver
* ALIAS: add navtest alias
* CI: format check all python files
=> ALIAS: add navtest alias

mission_control/navigator_missions/navigator_missions/move.py
=> MOVE: fix typo in circle operation

mission_control/navigator_launch/config/diagnostics.yaml, simulation/navigator_2dsim/launch/owl.launch, simulation/navigator_2dsim/sim2d.py
=> 2D SIM: fix drag to be proportional to velocity^2

gnc/navigator_controller/nodes/mrac_controller.py, mission_control/navigator_launch/launch/gnc.launch, mission_control/navigator_launch/launch/gnc/path_planner.launch, mission_control/navigator_missions/navigator_missions/__init__.py, mission_control/navigator_missions/navigator_missions/constant_velocity.py, mission_control/navigator_missions/navigator_missions/move.py, mission_control/navigator_missions/navigator_missions/navigator.py, mission_control/navigator_missions/navigator_missions/station_hold.py, navigator.rviz, scripts/bagging_variables.sh, simulation/navigator_gazebo/src/navigator_state_set.cpp, test/navigator_test/nodes/circle_sim.py
needed for ken to test thursters
=> MISSIONS: add mission to command constant velocity

doc/CMakeLists.txt, doc/high_level_architecture.dot, doc/package.xml
[See it here](https://svgur.com/i/8HR.svg)
=> DOCUMENTATION: add high level diagram

scripts/on_boot
=> BOOT: run passive sonar driver on boot

scripts/on_boot
* We cant put it in normal launch files b/c its proprietary software
=> BOOT: run sonar ros_bridge on boot

simulation/navigator_gazebo/package.xml, simulation/navigator_gazebo/worlds/course.world.xacro
=> SIMULATION: add obstacle course to gazebo

simulation/navigator_gazebo/urdf/navigator.urdf.xacro
=> SIMULATION: add shooter frame

mission_control/navigator_launch/launch/hardware.launch, mission_control/navigator_launch/launch/hardware/grinch_motor.launch, mission_control/navigator_launch/package.xml
depends on uf-mil/mil_common#156
=> LANUCH: launch motor driver for grinch

mission_control/navigator_missions/launch/task_runner.launch
values chosen from lakeday testing
closes #430
=> LAUNCHER: tune reload timing

mission_control/navigator_launch/launch/perception/pcodar.launch, mission_control/navigator_launch/launch/simulation.launch, simulation/navigator_gazebo/worlds/course.world.xacro
closes #438 
@BSpwr this adds the ring recovery reference buoy to SIM. It will be identifed in gazebo as "totem_violet"
=> SIMULATION: add ring recovery reference buoy

mission_control/navigator_missions/navigator_missions/navigator.py
@jaxnb 
@MarshallRawson 
Perhaps you can use this function on your mission to avoid duplicate code... I recall you doing something similar
=> MISSIONS: add get_sorted_objects function

mission_control/navigator_launch/config/pcodar.yaml, mission_control/navigator_launch/launch/perception/pcodar.launch, navigator.rviz
depends on uf-mil/mil_common#166
* Change launch/rivz config to work with PCODAR's new interactive markers
=> PCODAR: configuration changes to use interactive markers

mission_control/navigator_missions/navigator_missions/__init__.py, mission_control/navigator_missions/navigator_missions/navigator.py, mission_control/navigator_missions/navigator_missions/ring_recovery.py
=> MISSIONS: add RingRecovery mission

mission_control/navigator_launch/config/camera_calibration/seecam_C7500000.yaml, mission_control/navigator_launch/launch/hardware/cameras/starboard.launch
Don't merge until tested on platform Sunday
=> LAUNCH: use new seecam for starboard camera launch

utils/navigator_judgepanel/CMakeLists.txt, utils/navigator_judgepanel/package.xml, utils/navigator_judgepanel/src/UI.cpp, utils/navigator_judgepanel/src/UI.h, utils/navigator_judgepanel/src/UI.ui, utils/navigator_judgepanel/src/main.cpp, utils/navigator_judgepanel/src/package.xml, utils/navigator_msgs/CMakeLists.txt, utils/navigator_msgs/msg/ScanTheCode.msg, utils/navigator_msgs/srv/MessageScanCode.srv, utils/navigator_robotx_comms/navigator_robotx_comms/navigator_robotx_comms.py, utils/navigator_robotx_comms/nodes/robotx_comms_client.py, utils/navigator_robotx_comms/test/robotx_comms_server.py
Modified comms scan_code_message to send upon recieving /scan_the_code topic of type navigator_msgs::ScanTheCode. Updated GUI for 2018, GUI also recieves /scan_the_code for updating.
=> COMMS PROTOCOL/GUI : Update to use /scan_the_code subscriber

mission_control/navigator_launch/config/bounds_course_a.yaml, mission_control/navigator_launch/launch/gnc/bounds.launch
BOUNDS: update course A bounds
=> BOUNDS: add bounds for course A

mission_control/navigator_missions/navigator_missions/__init__.py, mission_control/navigator_missions/navigator_missions/obstacle_avoid.py
Closes #398 
Obstacle avoidance mission
Passed quals round at competition
Just needs some cleanup
=> Obstacle Avoid Mission
